// Run manually with `npm run build-font` whenever the pinned font weights
// change. Output is committed to api/_lib/font-data.js and required
// synchronously at runtime - no network fetch happens in the serverless
// functions themselves anymore (see the note in shared.js this replaced).

const fs = require('fs');
const path = require('path');

const CSS_URL = 'https://fonts.googleapis.com/css2?family=Chakra+Petch:wght@600;700&display=swap';
const OUT_PATH = path.join(__dirname, '..', 'api', '_lib', 'font-data.js');

async function main() {
  const cssRes = await fetch(CSS_URL, { headers: { 'User-Agent': 'Mozilla/5.0' } });
  if (!cssRes.ok) throw new Error(`Failed to fetch font CSS: ${cssRes.status}`);
  const css = await cssRes.text();

  const fontUrl = css.match(/url\((https:\/\/fonts\.gstatic\.com[^)]+)\)/)?.[1];
  if (!fontUrl) throw new Error('Could not find a woff2 URL in the fetched CSS');

  const fontRes = await fetch(fontUrl);
  if (!fontRes.ok) throw new Error(`Failed to fetch font file: ${fontRes.status}`);
  const buf = Buffer.from(await fontRes.arrayBuffer());

  const fontFace = `@font-face{font-family:'Chakra Petch';font-weight:600 700;src:url(data:font/woff2;base64,${buf.toString('base64')}) format('woff2');}`;

  const out = `// Generated by scripts/build-font.js - do not edit by hand.\n// Re-run that script and commit the new output if the pinned weights change.\nmodule.exports = ${JSON.stringify(fontFace)};\n`;
  fs.writeFileSync(OUT_PATH, out);
  console.log(`Wrote ${OUT_PATH} (${(buf.length / 1024).toFixed(1)} KB font embedded, ${(out.length / 1024).toFixed(1)} KB output file)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
